// <auto-generated />
using System;
using MesEntites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace MesEntites.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    partial class PersonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("countryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("countryName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("countryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            countryId = new Guid("da0a5d64-df49-4cd7-87cf-8b4939e07a33"),
                            countryName = "France"
                        },
                        new
                        {
                            countryId = new Guid("c70d400b-4ec4-4557-af98-0aa7b87d0230"),
                            countryName = "Espagne"
                        },
                        new
                        {
                            countryId = new Guid("25f18418-f2a6-4c36-8dfd-37c02fe86791"),
                            countryName = "Canada"
                        },
                        new
                        {
                            countryId = new Guid("0f916af0-87c1-44f2-a413-7c6d0e0ed344"),
                            countryName = "Suisse"
                        });
                });

            modelBuilder.Entity("MesEntites.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateofBirth")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PossedeLePermis")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivesNewsLetter")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("74a935fa-f2d4-40d7-8324-71406ffa82f7"),
                            Adress = "5th Floor",
                            CountryId = new Guid("0f916af0-87c1-44f2-a413-7c6d0e0ed344"),
                            Email = "jromeuf0@biglobe.ne.jp",
                            Gender = "Male",
                            PersonName = "Jefferson",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("5452c7d6-d58e-4760-8a9b-cc6ee6efe7e5"),
                            Adress = "PO Box 60084",
                            CountryId = new Guid("da0a5d64-df49-4cd7-87cf-8b4939e07a33"),
                            Email = "sgaddes1@arstechnica.com",
                            Gender = "Female",
                            PersonName = "Shalna",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("2a2d3ec6-2018-47ba-b6b6-68cc27ba877a"),
                            Adress = "Room 1550",
                            CountryId = new Guid("0f916af0-87c1-44f2-a413-7c6d0e0ed344"),
                            Email = "gkarlik2@cloudflare.com",
                            Gender = "Female",
                            PersonName = "Gilligan",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("4fa348f3-75c7-4176-b97c-3b1853f8f0fa"),
                            Adress = "Apt 52",
                            CountryId = new Guid("c70d400b-4ec4-4557-af98-0aa7b87d0230"),
                            Email = "ladolfsen3@taobao.com",
                            Gender = "Male",
                            PersonName = "Lars",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("a383c1df-6957-4cc6-adec-94886bf23967"),
                            Adress = "Apt 1480",
                            CountryId = new Guid("25f18418-f2a6-4c36-8dfd-37c02fe86791"),
                            Email = "tpryell4@china.com.cn",
                            Gender = "Female",
                            PersonName = "Tracy",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        },
                        new
                        {
                            PersonId = new Guid("21e761fa-4c90-4760-84ab-552e8b541471"),
                            Adress = "PO Box 24501",
                            CountryId = new Guid("0f916af0-87c1-44f2-a413-7c6d0e0ed344"),
                            Email = "dcharter5@devhub.com",
                            Gender = "Agender",
                            PersonName = "Dewey",
                            PossedeLePermis = false,
                            ReceivesNewsLetter = false
                        });
                });

            modelBuilder.Entity("MesEntites.Person", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
